#pragma config(Sensor, dgtl1,  sonarIn,        sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************************************************************
*
*  This file is meant as an introduction and as a template for developing
*  programs to run on the Vex controller.
*
*******************************************************************************/

/*******************************************************************************
*
*	main
*
*******************************************************************************/
task main()
{
//  int bumper = 1;	              // normal bumper state = 1; when pressed = 0

  wait1Msec(2000);    					// give stuff time to turn on

  while(true)
  {
  	//writeDebugStreamLine("The value of the light sensor is: %d", SensorValue[light3]);
    //Joystick control of the motors
    motor[leftMotor]   =  vexRT[Ch3];       // up = CW
    motor[rightMotor]  = -vexRT[Ch2];       // up = CCW
    //
    writeDebugStreamLine("The value of the sonar is: %d", SensorValue[sonarIn]);

    //If the bumper is press, automatically backup
  	  while(SensorValue[sonarIn] <= 25) // execute this loop when the sensor reads 10cm or closer
    {
	    writeDebugStreamLine("bumped-backing up");

    	motor[leftMotor] = -127; //fullspeed backwards
	    motor[rightMotor] = 127; //fullspeed backwards
	    wait1Msec(1000);  // keep backing up for 1000ms (1 sec)

	    motor[leftMotor]  = 0;  //stop motors
	    motor[rightMotor] = 0;  //stop motors
	    wait1Msec(1000);
     }

     writeDebugStreamLine("sensor is clear");
  }
}
