#pragma config(Sensor, dgtl1,  topen,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rearArmBotSense, sensorNone)
#pragma config(Sensor, dgtl4,  rearArmTopSense, sensorNone)
#pragma config(Sensor, dgtl7,  armChanger,     sensorNone)
#pragma config(Sensor, dgtl8,  botMotorButton, sensorNone)
#pragma config(Sensor, dgtl9,  topMotorButton, sensorNone)
#pragma config(Sensor, dgtl11, boten,          sensorQuadEncoder)
#pragma config(Motor,  port8,           baseMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           elbowMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************************************************************/

void takeDegrees(float deg) { //enter a value as a float, and this function will rotate the arm down that many degrees
	SensorValue[boten] = 0;
	while(abs(SensorValue[boten]) < (deg*4.3)) {
			motor(baseMotor) = 120;
		}
	motor(baseMotor) = 0;
}

void takeDegreesTwo(float deg, int dir) { //base motor
	SensorValue[boten] = 0;
	while(abs(SensorValue[boten]) < (deg*4.3)) {
			if (dir == 0) { //down
				motor(baseMotor) = 120;
			}
			else if (dir == 1) { //up
				motor(baseMotor) = -120;
			}
			else {
				writeDebugStreamLine("Error, will not turn");
			}
		}
	motor(baseMotor) = 0;
}

void takeDegreesThree(float deg, int dir, string mot) { //top motor
	SensorValue[topen] = 0;
	while(abs(SensorValue[topen]) < (deg*23.497)) {
			if (dir == 0) { //down
				motor(mot) = 50;
			}
			else if (dir == 1) { //up
				motor(mot) = -50;
			}
			else {
				writeDebugStreamLine("Error, will not turn");
			}
		}
	motor(baseMotor) = 0;
}


int thetatwo(int x, int y, int l1, int l2){
	return cos(90);
}

task main(){
	while(true){

	string thing;

		if (!SensorValue(armChanger)) {
				thing = elbowMotor;
		}

		else{
				thing = baseMotor;
		}

		writeDebugStreamLine("Encoder: %d", SensorValue(topen));

		if (!SensorValue(rearArmTopSense)) {
				SensorValue[topen] = 0;
			}
		else if (!SensorValue(rearArmBotSense)) {
			takeDegreesThree(90.000, 0, thing);
		}
		else if ((!SensorValue(botMotorButton)) && (!SensorValue(topMotorButton)) && (!SensorValue(rearArmTopSense))) {
		while(true){
				motor(baseMotor) = 0;
		}
	}

		else if (!SensorValue(botMotorButton)) {
			motor(thing) = 50;
		}
		else if (!SensorValue(topMotorButton)) {
			motor(thing) = -50;
		}
		else {
			motor(thing) = 0;
		}
	}
}
